# Generated by Django 5.1 on 2024-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="path",
            name="json_data",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="path",
            name="price",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddIndex(
            model_name="path",
            index=models.Index(
                fields=["name", "mark", "model"], name="search_path_name_23c755_idx"
            ),
        ),
    ]
