# Generated by Django 5.1 on 2024-08-08 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_path_json_data_path_price_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="path",
            new_name="part",
        ),
        migrations.RenameIndex(
            model_name="part",
            new_name="search_part_name_5673ca_idx",
            old_name="search_path_name_23c755_idx",
        ),
    ]
