# Generated by Django 5.1 on 2024-08-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0003_rename_path_part_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="part",
            name="search_part_name_5673ca_idx",
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["name", "mark", "is_visible"],
                name="search_part_name_65d42f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["json_data"], name="search_part_json_da_982276_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["mark", "is_visible"], name="search_part_mark_id_7a1032_idx"
            ),
        ),
    ]
