# Generated by Django 5.1 on 2024-08-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0005_remove_part_producer_country_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="part",
            name="search_part_name_65d42f_idx",
        ),
        migrations.RemoveIndex(
            model_name="part",
            name="search_part_json_da_982276_idx",
        ),
        migrations.RemoveIndex(
            model_name="part",
            name="search_part_mark_id_7a1032_idx",
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["name", "mark", "json_data", "is_visible"],
                name="search_part_name_7c5c35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["mark", "json_data", "is_visible"],
                name="search_part_mark_id_a57f57_idx",
            ),
        ),
    ]
